docs: add stuff favicons, coc, and initial config
pejuang-kode/pejuangkode.com pull request #2
Opened 2021-01-10 11:32 UTC by ekaone

Mas @zainfathoni sebagai initial kontribusi, feedbacknya highly appreciate, thanks anyway

2021-01-11 00:49 UTC, zainfathoni requested changes
Sudah saya tambahkan beberapa komentar dari saya ya Mas, terima kasih banyak atas bantuannya buat setup di awal ini. 😁

2021-01-11 00:49 UTC, zainfathoni commented on package.json
> +  "private": true,
Karena ini repository publik, dibuat `false` aja Mas. 😁 
```suggestion
  "private": false,
```

2021-01-11 00:49 UTC, zainfathoni commented on package.json
> +  "version": "1.0.0",
Sebelum kita mulai rilis di https://pejuangkode.com, sementara versinya biar tetep `0.0.1` dulu saja Mas. 😁 
```suggestion
  "version": "0.0.1",
```

2021-01-11 00:49 UTC, zainfathoni commented on package.json
> +    "next-seo": "^4.17.0",
Tolong dependency-nya dikunci ke versi ini dengan cara menghilangkan karakter _caret_ `^` ini supaya tidak ada perubahan yang tidak terencara Mas.
```suggestion
    "next-seo": "4.17.0",
```

2021-01-11 00:49 UTC, zainfathoni commented on package.json
> +    "url": "https://pejuankode.com"
```suggestion
    "url": "https://pejuangkode.com"
```

2021-01-11 00:49 UTC, zainfathoni commented on public/sitemap.xml
> +    <loc>https://pejuangkode.com</loc>
`sitemap.xml` ini bisa di-generate secara otomatis atau harus di-_update_ secara manual Mas @ekaone?

2021-01-11 02:47 UTC, ekaone commented on package.json
> +  "version": "1.0.0",
Yes correct 😁

2021-01-11 02:49 UTC, ekaone commented on package.json
> +    "next-seo": "^4.17.0",
Setuju, untuk menghindari error antar dependecy 👌

2021-01-11 02:51 UTC, ekaone commented on package.json
> +    "url": "https://pejuankode.com"
Kadang suka miss, kemarin sempat nulis pujanggakode.com 😄, thanks koreksinya

2021-01-11 02:57 UTC, ekaone commented on public/sitemap.xml
> +    <loc>https://pejuangkode.com</loc>
Ini masih manual dan sebagai persiapan kalau dibutuhkan, harusnya bisa generate otomatis, mungkin [ini](https://github.com/iamvishnusankar/next-sitemap#readme) dan [ini](https://github.com/IlusionDev/nextjs-sitemap-generator) bisa jadi pertimbangan

2021-01-11 03:08 UTC, ekaone commented
Terima kasih feedbacknya 🙏, sekiranya ada yang ingin ditambahkan misal content-delivery, struktur direktori, dan lainnya, kita lanjut di Discussion

2021-01-11 03:12 UTC, zainfathoni commented
Kenapa di-_close_ Mas @ekaone? 😅 
Harusnya udah siap _merge_ ini. 😁

2021-01-11 03:16 UTC, zainfathoni commented on public/sitemap.xml
> +    <loc>https://pejuangkode.com</loc>
Oke Mas, setidaknya sekarang sudah ada dulu sebagai pengingat bahwa kita perlu sitemap.xml. 😉

2021-01-11 03:16 UTC, zainfathoni approved these changes

2021-01-11 03:17 UTC, merged

2021-01-11 04:16 UTC, ekaone commented
😄 iya ada notif `Merge Block` perihal Signed, belum sempat explorer cara pakainya Signed itu 😁. Mau tanya, kalau URL yang https://pejuangkode.vercel.app untuk apa ya..?, kalau URL [previewnya](https://pejuangkode-dl97hat7m.vercel.app/) yang dari Vercel sudah jalan, karena ini berkaitan dengan file `next-seo.config.js` di root direktori di property `openGraph.images.url`, ini untuk biar banner.jpg bisa keluar ketika post link URL di media social (Twitter, FB, Discord dll)

2021-01-22 23:22 UTC, zainfathoni commented
> 😄 iya ada notif `Merge Block` perihal Signed, belum sempat explorer cara pakainya Signed itu 😁. Mau tanya, kalau URL yang https://pejuangkode.vercel.app untuk apa ya..?, kalau URL [previewnya](https://pejuangkode-dl97hat7m.vercel.app/) yang dari Vercel sudah jalan, karena ini berkaitan dengan file `next-seo.config.js` di root direktori di property `openGraph.images.url`, ini untuk biar banner.jpg bisa keluar ketika post link URL di media social (Twitter, FB, Discord dll)

Mas @ekaone bisa belajar terkait Git Commit Signing [di sini](https://github.com/zainfathoni/obel/blob/master/CONTRIBUTING.md#git-commits-signing). 😁 

URL yang dari Vercel itu sudah siap buat production Mas, tapi sekarang domain pejuangkode.com-nya belum bisa kita arahkan ke sana karena yg project yg ini masih belum siap publish.
Kalau mau gambarnya muncul di pejuangkode.com, paling solusinya ya kita pakai domain pejuangkode.vercel.com dulu saja untuk sementara waktu ini. 😁